import * as React from "react";
import { ContribPageWithHeader } from "./PageWithHeader/ContribPageWithHeader";
import { ChooseGroupPage } from "./ChooseGroup/ChooseGroupPage";
import { Page } from "../../shared/components/PageWithHeader/Page";

export class TouchstoneHelp extends ContribPageWithHeader<undefined> {
    name() {
        return "Touchstones Help";
    }

    urlFragment() {
        return "help/touchstones/";
    }

    parent() {
        return new ChooseGroupPage();
    }

    render() :JSX.Element {
        return <Page page={this}>
            <p>
                To distinguish between the different sets of impact estimates
                generated by the consortium over time, we use the concept of the
                'touchstone', which uniquely defines the version in terms of model
                version and associated assumptions as well as input datasets, in
                particular regarding vaccination coverage.
            </p>
            <p>
                There are two types of touchstones:
                <ol>
                    <li>
                        Touchstones containing 'native' model runs, as supplied by the
                        modelling groups. These are the ones directly generated by consortium
                        members.
                    </li>
                    <li>
                        Touchstones containing 'modified updates' of the native runs,
                        updating estimates between the major re-runs with new assumptions
                        regarding vaccination coverage. Modified updates are performed by the
                        consortium's secretariat without input from consortium members.
                    </li>
                </ol>
            </p>
            <div className="subSectionTitle">Touchstone naming conventions</div>
            <p>
                Touchstones are named by the date when they were generated (format
                yyyymm), and a text string determining the assumptions of the
                underlying vaccination coverage set ('gavi' for using Gavi's SDF
                projections, 'wue' when WUENIC estimates of past vaccination coverage
                are used (together with Gavi's records of past campaigns that have
                been performed).
            </p>
            <p>
                Native touchstones will only have one part to their name, and will
                usually be based on Gavi's coverage projections. The upcoming
                touchstone for the 2017 run of impact estimates will be '201710gavi',
                while we currently ask you to generate estimates associated with the
                test runs that are part of the touchstone '201708test'.
            </p>
            <p>
                Modified updates will be labelled with the same name as the native
                touchstone which estimates are updated, followed by a second part
                determining the vaccination coverage used in the update. For instance,
                the touchstone '201510gavi-201707wue' refers to the last set of impact
                estimates generated in autumn 2015 based on SDF12, updated with the
                new WUENIC coverage published in July 2017.
            </p>
        </Page>;
    }
}