#!/usr/bin/env bash
ORG=vimc

if [ "$BUILDKITE" = "true" ]; then
    GIT_SHA=${BUILDKITE_COMMIT:0:7}
else
    GIT_SHA=$(git rev-parse --short=7 HEAD)
fi

if [ "$BUILDKITE" = "true" ]; then
    GIT_BRANCH=$BUILDKITE_BRANCH
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

BUILD_ENV_TAG=$ORG/montagu-portal-shared-build-env:$GIT_SHA
