steps:
  - label: ":construction_worker: Make shared build env"
    command: buildkite/make-build-env.sh

  - wait

  - label: ":shipit: Build and push app images"
    command: buildkite/run-build.sh

  - label: ":construction_worker: Build and push integration test image"
    command: buildkite/make-integration-tests-image.sh
