export const header: string;
export const header__siteTitle: string;
export const headerSiteTitle: string;
export const titleAddition: string;
export const page: string;
export const page__title: string;
export const pageTitle: string;
export const page__content: string;
export const pageContent: string;
