import * as React from "react";

import {settings} from "../../../../shared/Settings";
import {InternalLink} from "../../../../shared/components/InternalLink";
import {PageArticle} from "../../../../shared/components/PageWithHeader/PageArticle";
import {PageProperties} from "../../../../shared/components/PageWithHeader/PageProperties";
import {TouchstoneVersion} from "../../../../shared/models/Generated";
import {ResponsibilityOverviewPageLocationProps} from "./ResponsibilityOverviewPage";

interface ResponsibilityOverviewDescriptionProps {
    currentTouchstoneId: string;
    groupId: string;
    touchstoneStatus: string;
}

const outputGuide = require("./outputs-guide.pdf");


const ContactDetails = () => {
    return <div>
        If you have any questions or anything is not as you expected, please email&nbsp;
        <a href={`mailto:${settings.supportContact}`}>
                        {settings.supportContact}
                    </a>
        &nbsp;or use the #montagu-help
                    channel on&nbsp;
        <a href={settings.slackUrl} target="_blank">Slack</a>.
    </div>
}

const JanuaryRfpTouchstone = () => {
    return <div>
        On this page you can:
        <ul>
            <li>
                Access the standardised demographic data (Most of the demographic data is based on the UN
                World Population Prospects (UNWPP) 2017 Revision).
            </li>
            <li>
                Download the burden estimate templates for your disease area.
            </li>
            <li>
                Submit the burden estimates generated by your model for one country of choice.
            </li>
        </ul>
        Output specifications guidance is available on the VIMC website (<a
        href="https://www.vaccineimpact.org/2017-12-19-request-for-proposals-yellow-fever-rubella-Japanese-encephalitis-closing-date-January-30/"
        target="_blank">
        https://www.vaccineimpact.org/2017-12-19-request-for-proposals-yellow-fever-rubella-Japanese-encephalitis-closing-date-January-30/</a>).
        <ContactDetails/>
    </div>;
};


export const ResponsibilityOverviewDescription = (props: ResponsibilityOverviewDescriptionProps) => {
    if (props.touchstoneStatus !== "open"){
        return  <div>
            <div className="alert alert-danger">This touchstone is no longer open.</div>
            <ContactDetails/>
        </div>;
    }

    if (settings.isApplicantTouchstone(props.currentTouchstoneId)) {

        return JanuaryRfpTouchstone()

    } else {
        const guidanceInputsUrl = `/help/model-inputs/${props.currentTouchstoneId}`;
        const guidanceOutputsUrl = `/help/model-outputs/${props.currentTouchstoneId}`;

        let templatesInfo;
        let outputGuidanceLinkText;
        let stochasticEstimatesText;

        if (settings.isVersionOfStochasticTouchstone(props.currentTouchstoneId))
        {
            templatesInfo = <li>
                                Download csv templates for central and stochastic burden estimates,
                                and for underlying parameter values.
                            </li>;
            outputGuidanceLinkText = "Guidance on model outputs: how to generate and upload central and stochastic estimates";
            stochasticEstimatesText = "In the future, you will also be able to upload stochastic burden estimates for each scenario."
        }
        else
        {
            templatesInfo = <li>
                                Download csv templates for central burden estimates.
                            </li>;
            outputGuidanceLinkText = "Guidance on model outputs: how to generate and upload central estimates";
            stochasticEstimatesText = "Stochastic estimates are not required for this touchstone. Please provide central estimates only";
        }

        return <div>
            On this page you can:
            <ul>
                <li>
                    See an overview of which scenarios your group is responsible
                    for providing burden estimates for.
                </li>
                <li>
                    Download vaccination coverage data for each scenario.&nbsp;
                    <InternalLink href={guidanceInputsUrl}>
                        More guidance here
                    </InternalLink>.
                </li>
                <li>
                    Download demographic data which applies to all scenarios.
                    Please use the demographic datasets supplied to ensure consistency
                    between all models.&nbsp;
                    <InternalLink href={`${guidanceInputsUrl}#demography`}>
                        More guidance here
                    </InternalLink>.
                </li>
                {templatesInfo}
                <li>
                    Upload central burden estimates for each scenario, and review any
                    problems the system has detected in the uploaded data.&nbsp;
                    <InternalLink href={guidanceOutputsUrl}>
                        More guidance here
                    </InternalLink>.
                </li>
                {
                    settings.isVersionOfStochasticTouchstone(props.currentTouchstoneId) &&
                    <li>
                        Upload your parameters file.&nbsp;
                        <InternalLink href={guidanceOutputsUrl}>
                            More guidance here
                        </InternalLink>.
                    </li>
                }
            </ul>
                <p>
                    {stochasticEstimatesText}
                </p>
            <span>
                    Useful links:
                </span>
            <ul>
                <li>
                    <InternalLink href={guidanceInputsUrl}>
                        Guidance on model inputs: coverage and demographic data
                    </InternalLink>
                </li>
                <li>
                    <InternalLink href={guidanceOutputsUrl}>
                        {outputGuidanceLinkText}
                    </InternalLink>
                </li>
            </ul>
            <ContactDetails />
        </div>;
    }
};
