import {PageArticle} from "../../../../../shared/components/PageWithHeader/PageArticle";
import ScrollableAnchor from "react-scrollable-anchor";
import {InternalLink} from "../../../../../shared/components/InternalLink";
import {settings} from "../../../../../shared/Settings";
import * as React from "react";
import {mapStateToGuidanceContentProps, ResponsibilityGuidanceContentProps} from "./ResponsibilityGuidanceContentProps";
import {connect} from "react-redux";

export class ResponsibilityGuidanceModelInputsContent2019Component extends React.Component<ResponsibilityGuidanceContentProps> {

    render(): JSX.Element {

        return <PageArticle title="Guidance on model inputs: coverage and demographic data">
            <div className="alert alert-primary">Guidance for
                touchstone {this.props.touchstoneVersion.description}</div>
            <div className="largeSectionTitle">
                Input data sources
            </div>
            <p>
                Both coverage and demographic datasets to be used in the full
                model runs are available for download through Montagu. Please
                download and use these datasets, rather than your own datasets
                to ensure consistency of estimates across the Consortium.
            </p>
            <div className="largeSectionTitle">
                Coverage
            </div>
            <p>
                Coverage for the 201910 full model runs will not be linked to Gavi’s Operational Forecast. Instead,
                ‘best case’ and ‘default’ coverage is generated by Gavi and the VIMC secretariat, based on agreed
                assumptions.
                The aim of using ‘default’ coverage is two-fold:
                <ul>
                    <li>to allow the VIMC secretariat to generate impact ratios (e.g. deaths averted per fully
                        vaccinated
                        person) for every country/vaccine combination
                    </li>
                    <li>to avoid the sensitivities of Gavi’s Operational Forecast</li>
                </ul>
                To achieve the first aim, the default coverage assumes some coverage exists for every country/vaccine
                combination, in at least one year (up to and including 2030). This assumption is made solely to allow
                the VIMC secretariat to generate impact ratios. It should not be taken as an indication that all
                countries will introduce all vaccines by 2030, or that the 2031-2100 coverage projections are likely to
                be achieved.
            </p>
            <table>
                <tbody>
                <tr>
                    <th> Variant</th>
                    <th> Country set</th>
                    <th> Period</th>
                    <th> Type</th>
                    <th> Source</th>
                </tr>

                <tr>
                    <td> Default</td>
                    <td> VIMC 112</td>
                    <td> Up to 2018</td>
                    <td> Routine</td>
                    <td> WUENIC (and other historial records)</td>
                </tr>
                <tr>
                    <td> Default</td>
                    <td> VIMC 112</td>
                    <td> Up to 2018</td>
                    <td> Campaign</td>
                    <td> Records of past campaigns from Gavi and other sources</td>
                </tr>
                <tr>
                    <td> Default</td>
                    <td> VIMC 112</td>
                    <td> 2019-2030</td>
                    <td> Routine</td>
                    <td> Gavi default assumptions</td>
                </tr>
                <tr>
                    <td> Default</td>
                    <td> VIMC 112</td>
                    <td> 2019-2030</td>
                    <td> Campaign</td>
                    <td> Gavi default assumptions</td>
                </tr>
                <tr>
                    <td> Default</td>
                    <td> VIMC 112</td>
                    <td> 2031-2100</td>
                    <td> Routine</td>
                    <td> Extrapolated by VIMC from Gavi default assumptions: 1% increase per year, up to a maximum
                        threshold. The maximum threshold is (a) or (b), whichever is highest:
                        a) 90% (or 95% for MCV1)
                        b) highest routine coverage value for the country/vaccine combination in question, in any year
                        up to (and including) 2030
                    </td>
                </tr>
                <tr>
                    <td> Default</td>
                    <td> VIMC 112</td>
                    <td> 2031-2100</td>
                    <td> Campaign</td>
                    <td> Assume no campaigns in this period</td>
                </tr>
                <tr>
                    <td> Best case</td>
                    <td> VIMC 112</td>
                    <td> Up to 2020</td>
                    <td> Routine and campaign</td>
                    <td> "Best case" coverage to match "Default" (see above)</td>
                </tr>
                <tr>
                    <td> Best case</td>
                    <td> VIMC 112</td>
                    <td> 2021-2100</td>
                    <td> Routine</td>
                    <td> Based on VIMC assumptions:
                        Routine coverage is constant at 90% (95% for MCV1) for 2021-2100. Exceptions: if coverage in any
                        year up to and including 2020 is greater than 90% (95% for MCV1), use this coverage value for
                        2021-2100.
                    </td>
                </tr>
                <tr>
                    <td> Best case</td>
                    <td> VIMC 112</td>
                    <td> 2021</td>
                    <td> Campaign</td>
                    <td>Based on VIMC assumptions:

                        Rubella, MenA, HPV: for countries where the default scenario indicates no routine coverage in
                        2020, assume a national level catch-up campaign in 2021, targeting typical age groups. Campaign
                        coverage will be 95%.

                        Rubella, MenA, HPV: for countries where the default scenario indicates routine coverage in 2020,
                        assume no campaign in 2021.

                        YF and JE: Regardless of whether the vaccine has already been introduced, assume a campaign in
                        2021, targeting typical age groups. Campaign coverage will be 95%.

                        Measles - no campaigns in 2021.

                    </td>
                </tr>
                <tr>
                    <td> Best case</td>
                    <td> VIMC 112</td>
                    <td> 2022-2100</td>
                    <td> Campaign</td>
                    <td> Assume no campaigns in this period</td>
                </tr>
                </tbody>
            </table>
            <br/>
            <p>
                Each modelling group has several scenarios for ‘default’ and several scenarios for ‘best case’. In
                addition, all groups have a ‘no vaccination’ scenario. Some groups also have a ‘stop scenario’ which
                mirrors the default coverage for years up to and including 2020, and then switches to zero coverage for
                2021 onwards. ‘Best case’, ‘default’ and ‘stop’ scenarios will have the same coverage up to and
                including 2020.
            </p>
            <p>
                Each scenario has one ‘combined coverage dataset’, which is downloadable as one single CSV file. This
                file may include coverage from several coverage sets, e.g. routine 1st dose, routine 2nd dose, and
                campaigns. The specific coverage sets included within each download are shown on the download page.
            </p>
            <p>
                There are no coverage sets included in the no vaccination scenario, and therefore this coverage download
                file does not contain any data apart from the header row.
            </p>
            <p>
                <b>gavi_support</b> can be ignored. All column values are "total"; this means either Gavi-funded or not
                Gavi-funded.
            </p>
            <p>
                <b>age_range_verbatim</b> is a description of the age range. We have used this to
                infer <b>age_first</b> and <b>age_last</b>. Where age_range_verbatim is "NA", this indicates the default
                age_first and age_last value for that vaccine.
            </p>
            <p>
                <b>coverage</b> shows the level of vaccination coverage, usually ranging from 0 (0%) to 1 (100%). In
                some cases, this value may be greater than 1. For example, if a campaign originally targets 1 million
                people but ends up vaccinating 1.1 million people, the coverage would be shown as 1.1 (equating to
                110%).
            </p>
            <p>
                Coverage and target population are now always specified at a national level. For example, where a
                campaign targets all ages in Region A (population 1,000,000) and achieves 90% coverage, and where the
                population of the whole country is 5,000,000, the coverage would appear on Montagu as 0.18 (18%) and the
                target population as 5,000,000. This way of specifying coverage and target population applies in both
                past and future years.
            </p>
            <p>
                <b>target</b> is the number of individuals in the target population. This is always shown for campaigns,
                and is now specified at a national level. (See ‘coverage’ section above.) For routine, target is shown
                as <b>NA</b>, which means you should assume the target population matches the population shown in the
                demographic data downloads for the corresponding ages (age_first and age_last). HPV modellers should
                also filter the demographic downloads by gender=female.
            </p>
            <ScrollableAnchor id={'demography'}>
                <div className="largeSectionTitle">
                    Demography
                </div>
            </ScrollableAnchor>
            <p>
                <b>Q. What is the source of the demographic data provided via Montagu
                    for the 201810 touchstone?</b>
            </p>
            <p>
                A. Most of the demographic data is based on the&nbsp;
                <a href="https://population.un.org/wpp/" target="_blank">
                    UN World Population Prospects (UNWPP) 2019 Revision
                </a>.
                Some fields were augmented to
                fill particular gaps; descriptions for these can
                be found here:
            </p>
            <ul>
                <li>
                    <InternalLink href="/help/neonatal-mortality/">
                        Neonatal mortality
                    </InternalLink> - using the <a href={"https://childmortality.org"} target={"_blank"}>IGME 2018
                    release (Sep 2019)</a>
                </li>
                <li>
                    <InternalLink href="/help/kosovo/">
                        Kosovo
                    </InternalLink> - using the most recent <a
                    href={"http://ask.rks-gov.net/en/kosovo-agency-of-statistics/add-news/population-estimation-2018"}
                    target={"_blank"}>population estimates</a> from Kosovo Agency of Statistics
                </li>
                <li>
                    <InternalLink href="/help/marshall-islands/">
                        Marshall Islands
                    </InternalLink>
                </li>
                <li>
                    <InternalLink href="/help/tuvalu/">
                        Tuvalu
                    </InternalLink>
                </li>
                <li>
                    <a href={"https://montagu.vaccineimpact.org/reports/report/internal-2018-demography-pre1950/20180524-142831-4228995a"}>Back-projection
                        to birth for cohorts alive in 1950</a>
                </li>
            </ul>
            Note that prior to 2019, we also calculated populations in single year bands for ages over 80 prior to 1990;
            this is now carried out by UNWPP.
            <p>
                <b>Q. Can I use a different set of demographic data, rather
                    than the set provided on Montagu?</b>
            </p>
            <p>
                A. No. In order to ensure consistency between all models, you
                must use the demographic data provided via Montagu.
            </p>
            <p>
                <b>Q. Why does male + female not equal the total population?</b>
            </p>
            <p>
                A. This is a property of the UNWPP data; they provide separate
                data for male, female, and total, and we provide the same data.
            </p>
            <p>
                <b>Q. Why is population at birth (age 0) not the same as the
                    number of births?</b>
            </p>
            <p>
                A. In UNWPP data, age '0-0' refers to all people under 1 year
                old on a particular reference day. This will differ from the
                number of births into this cohort during the year due to the
                timing, and the effects of infant mortality and migration.
            </p>
            <p>
                <b>Q. I require demographic data that isn't available on Montagu.
                    What should I do?</b>
            </p>
            <p>
                A. Please contact us at&nbsp;
                <a href={`mailto:${settings.supportContact}`}>
                    {settings.supportContact}
                </a>
                &nbsp;or use
                the #montagu-help channel on&nbsp;
                <a href={settings.slackUrl} target="_blank">
                    Slack
                </a>.
            </p>
            <p>
                <b>Q. Can I download all demographic data in one download?</b>
            </p>
            <p>
                A. We are working on this functionality for future runs, but
                for the current runs you will need to download each demographic
                dataset separately.
            </p>
        </PageArticle>
    }
}

export const ResponsibilityGuidanceModelInputsContent2019 = connect(mapStateToGuidanceContentProps)(ResponsibilityGuidanceModelInputsContent2019Component);